name: dmp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pytorch # 2.5.1
  - torchvision # 0.20.1
  - torchaudio # 2.5.1
  - transformers # 4.54.1
  - openai
  - pandas
  - tqdm
  - scikit-learn
  - matplotlib
  - rouge-score
  - sentence-transformers
  - evaluate
  - datasets
  - ipdb
  - pandarallel
  - pip
  - pip:
      - persist_to_disk
      - selfcheckgpt 
      - accelerate
      - torchmetrics
      - wandb
      - tiktoken
      - tenacity